services:
  - type: web
    name: scraper-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn scrape.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
    
  - type: web
    name: remix-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn remix.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true